server:
  port: 8081

application:
  title: Hospital Service
  version: 1.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospitaldb
    username: root
    password: hospitalroot
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 24
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/master-changelog.yaml
    default-schema: hospitaldb
  banner:
    location: classpath:/banner/hospital-banner.txt